export const ADD_EXPENSE = 'ADD_EXPENSE';
export const SET_MONTHLY_EXPENSE_DETAILS = 'SET_MONTHLY_EXPENSE_DETAILS';
export const SET_CATEGORY_WISE_EXPENSE_FOR_ALL_MONTHS = 'SET_CATEGORY_WISE_EXPENSE_FOR_ALL_MONTHS';
