export const CATEGORIES = [
  'Home & Utility',
  'Transport',
  'Food & Drinks',
  'Health & Personal Care',
  'Clothing & Footwear',
  'Education',
  'Gifts',
  'Celebrations',
  'Charity',
  'Entertainment',
  'Loans',
  'Sports',
  'Others',
];
